//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int id { get; set; }
        public int CompanyID { get; set; }
        public string Brand1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBY { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string ModiBy { get; set; }
        public Nullable<System.DateTime> ModiOn { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
