//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeDA
    {
        public int id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> GratdeID { get; set; }
        public string DAType { get; set; }
        public string Description { get; set; }
        public Nullable<double> DARate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreadedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Grade Grade { get; set; }
    }
}
