//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventryItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventryItem()
        {
            this.Accesories = new HashSet<Accesory>();
            this.BranchStocks = new HashSet<BranchStock>();
            this.Issues = new HashSet<Issue>();
            this.ItemAttributes = new HashSet<ItemAttribute>();
            this.Receipts = new HashSet<Receipt>();
            this.ReturnItems = new HashSet<ReturnItem>();
            this.WeighBridgeItemValues = new HashSet<WeighBridgeItemValue>();
        }
    
        public int id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CatID { get; set; }
        public string PurchaseDescription { get; set; }
        public string SalesDescription { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<double> AvgPurchasePrice { get; set; }
        public Nullable<double> LastPurchasePrice { get; set; }
        public Nullable<double> BottemPrice { get; set; }
        public Nullable<double> InternalPrice { get; set; }
        public Nullable<double> TradesPrice { get; set; }
        public Nullable<double> QoutedPrice { get; set; }
        public Nullable<double> AvgSalePrice { get; set; }
        public Nullable<double> LastSalePrice { get; set; }
        public Nullable<System.DateTime> LastRecived { get; set; }
        public Nullable<System.DateTime> LastIssue { get; set; }
        public Nullable<System.DateTime> LastReturn { get; set; }
        public Nullable<System.DateTime> LastTransfer { get; set; }
        public Nullable<System.DateTime> LastInTransit { get; set; }
        public Nullable<System.DateTime> LastScrap { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifedOn { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> ManFaceID { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesory> Accesories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchStock> BranchStocks { get; set; }
        public virtual Company Company { get; set; }
        public virtual Manufactuere Manufactuere { get; set; }
        public virtual Model Model { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAttribute> ItemAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnItem> ReturnItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeighBridgeItemValue> WeighBridgeItemValues { get; set; }
    }
}
