//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageBranchStock
    {
        public int Id { get; set; }
        public int BranchID { get; set; }
        public int Quantity { get; set; }
        public string CreatedBy { get; set; }
        public int WeighBridgeID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual WeighBridge WeighBridge { get; set; }
    }
}
