//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnItem
    {
        public int Id { get; set; }
        public int BranchID { get; set; }
        public int ItemID { get; set; }
        public double QuantityReturn { get; set; }
        public double PriceChargeReturn { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReturnedBranchID { get; set; }
        public string ReturnBy { get; set; }
        public System.DateTime ReturnedOn { get; set; }
        public string ReturnDocument { get; set; }
        public string ReturnRemarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string Status { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
        public virtual Cutomer Cutomer { get; set; }
        public virtual inventryItem inventryItem { get; set; }
    }
}
