//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string UserCal1 { get; set; }
        public string UserCal2 { get; set; }
        public string Password { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PerAddress1 { get; set; }
        public string PerAddress2 { get; set; }
        public string PerCity { get; set; }
        public string PerCountry { get; set; }
        public Nullable<int> DesigantionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string ReportingMgr { get; set; }
        public string PictuerPath { get; set; }
        public Nullable<System.DateTime> JoininDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public string CraatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UserType { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Grade Grade { get; set; }
    }
}
