//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeighBridgeItemValue
    {
        public int Id { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public int WeighBridgeID { get; set; }
        public int BranchID { get; set; }
        public Nullable<double> PackagePurchasePrice { get; set; }
        public Nullable<double> PackageSalePrice { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual inventryItem inventryItem { get; set; }
        public virtual WeighBridge WeighBridge { get; set; }
    }
}
